title: RST
description: Documentation for RST - Revenge System Tools. Python bot created by RevengeFir for easy system monitoring and more. 
theme: just-the-docs

url: https://github.com/revengefir/rst

aux_links:
  botrepo: https://github.com/revengefir/rst
